### PR TITLE
Add logging. Use systemd.

### PR DESCRIPTION
**Pull request by jcksnvllxr80**

### CODE REVIEW

**Comment by jcksnvllxr80** [comment]
1. I updated the readmes but they could definitely use more love since i added so much and didnt fine-tooth them.
2. I moved the scripts to the place in the build folder (maintaining the script in two places would be a tiny nightmare) where they will go in the system (i.e. /usr/bin/berryCam). I'm not sure how you feel about that but the READMEs suffer because of that move and i didnt go back through and fix all of that :/
3. Maybe this should be a branch called berrycam-service??

**Comment by fotosyn** [comment]
Thanks for this and apologies for not getting back. I've been a tad under the weather this week and not getting as much screen time as I usually would. 

Let me take a look later this week and come back with some suggestions - thinking that we potentially branch this version so that the other route still exists as well as this improved, service based approach. That gives the user a choice to opt for whichever version they are most comfortable with

**Comment by fotosyn** [comment]
Fantastic work by the way, might be good to pick your brains on how a live streaming version could work with BerryCam.

**Comment by jcksnvllxr80** [comment]
Maybe we can put the file at /home/pi and use a link (hard/soft) to put it at /usr/bin as well... this way only one file needs to be maintained. At the same time I can remove the automatic enabling of the service so it doesnt run on boot and if the user wants to enable it, they can do that with a command... but if not, it still works the same way you already have it setup.
I just need to do some testing to see if that will be feasible.

**Pull request closed without merging**
